services:
  whisper-pipeline:
    build: 
      context: ./whisper-pipeline
      dockerfile: Dockerfile
    container_name: whisper-pipeline
    restart: unless-stopped
    volumes:
      - /docker/whisper/data/videos:/app/data/videos
      - /docker/whisper/data/audio:/app/data/audio
      - /docker/whisper/data/transcripts:/app/data/transcripts
      - /docker/whisper/data/models:/app/data/models
      - /docker/whisper/data/logs:/app/data/logs
    environment:
      - MODEL_SIZE=small
      - LANGUAGE=en
      - THREADS=4
      - DEVICE=cpu
      - SCAN_INTERVAL=120
    mem_limit: 2g
    mem_reservation: 1g
