services:
  whisper-pipeline:
    build: 
      context: ./whisper-pipeline
      dockerfile: Dockerfile
    container_name: whisper-pipeline
    restart: unless-stopped
    volumes:
      - whisper_videos:/app/data/videos
      - whisper_audio:/app/data/audio
      - whisper_transcripts:/app/data/transcripts
      - whisper_models:/app/data/models
      - whisper_logs:/app/data/logs
    environment:
      - MODEL_SIZE=small
      - LANGUAGE=en
      - THREADS=4
      - DEVICE=cpu
      - SCAN_INTERVAL=120
    mem_limit: 2g
    mem_reservation: 1g

volumes:
  whisper_videos:
  whisper_audio:
  whisper_transcripts:
  whisper_models:
  whisper_logs:
